//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotChamp.Models.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailServiceCred {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailServiceCred() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GotChamp.Models.Email.EmailServiceCred", typeof(EmailServiceCred).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string AnonymousPort {
            get {
                return ResourceManager.GetString("AnonymousPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relay-hosting.secureserver.net.
        /// </summary>
        public static string AnonymousServer {
            get {
                return ResourceManager.GetString("AnonymousServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 993.
        /// </summary>
        public static string IncomingPortWithSSL {
            get {
                return ResourceManager.GetString("IncomingPortWithSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 143.
        /// </summary>
        public static string IncomingPortWOSSL {
            get {
                return ResourceManager.GetString("IncomingPortWOSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imap.secureserver.net.
        /// </summary>
        public static string IncomingServer {
            get {
                return ResourceManager.GetString("IncomingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3535.
        /// </summary>
        public static string OutgoingPortWOSSL {
            get {
                return ResourceManager.GetString("OutgoingPortWOSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 465.
        /// </summary>
        public static string OutgoingPortWSSL {
            get {
                return ResourceManager.GetString("OutgoingPortWSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtpout.secureserver.net.
        /// </summary>
        public static string OutgoingServer {
            get {
                return ResourceManager.GetString("OutgoingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pa$$w0rd##.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gotchamp.project@blastasia.us.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
