//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotChamp.Models.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GotChamp.Models.Email.MessageTemplate", typeof(MessageTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string MessageClose {
            get {
                return ResourceManager.GetString("MessageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MessageCombination {
            get {
                return ResourceManager.GetString("MessageCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/p&gt;.
        /// </summary>
        public static string MessageHeaderClose {
            get {
                return ResourceManager.GetString("MessageHeaderClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi! .
        /// </summary>
        public static string MessageHeaderOpen {
            get {
                return ResourceManager.GetString("MessageHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;Welcome to &lt;b style=&quot;font-size: 1.2em;&quot;&gt;Gotchamp!&lt;/b&gt; Thank you for joining our online number game that give benefits and aid to those who needed the most.&lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;center style=&quot;font-size: 1.2em;&quot;&gt;&lt;b&gt;You can start playing now!&lt;/b&gt;&lt;/center&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;center style=&quot;font-size: 1.2em;&quot;&gt;&lt;b&gt;Enjoy, Have Fun, and Good Luck! See You!&lt;/b&gt;&lt;/center&gt;&lt;/p&gt;
        ///
        ///&lt;i style=&quot;font-size: .8em;&quot;&gt;This message was generated by Gotchamp. If you believe you got it by mistake, &lt;a href=&quot;www.google.co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MessageNotify {
            get {
                return ResourceManager.GetString("MessageNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;title&gt;
        ///        
        ///    &lt;/title&gt;
        ///    &lt;body&gt;
        ///        &lt;div style=&quot;font-family: calibri; width: 60%; margin: auto; font-size: 1.5em;&quot;&gt;.
        /// </summary>
        public static string MessageOpen {
            get {
                return ResourceManager.GetString("MessageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MessageRecover {
            get {
                return ResourceManager.GetString("MessageRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gotchamp Online Lotto.
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
    }
}
